# Instituto Tecnologico de Durango 

# Analítica de Datos en las Organizaciones

# Alumna: Brenda Raquel Sanchez Alanis 

# Docente: José Gabriel Rodríguez Rivas



# Unidad Il   

## Laboratorio 3

In [5]:
import datetime
import csv
import subprocess

In [6]:
date_time  =  datetime.datetime.now()
print(date_time)

2022-09-29 13:25:00.978946

In [7]:
date_time.strftime('%a, %d %d %Y %H:%M:%S')

'Thu, 29 29 2022 13:25:00'

In [8]:
# Celda de código 6 
# Esta cadena contiene la línea de comando para interactuar con speedtest.net 
speedtest_cmd  =  "speedtest-cli --simple" 
# Ejecutar el proceso 
process  =  subprocess . Popen ( speedtest_cmd . split (),  stdout = subprocess . PIPE ) 
# Recopile la salida del comando 
process_output  =  process .communicate  ()[ 0 ]

In [9]:
print(process_output, type(process_output))

b'Ping: 85.008 ms\r\nDownload: 68.61 Mbit/s\r\nUpload: 37.95 Mbit/s\r\n' <class 'bytes'>

In [10]:
# Celda de código 8 
# Almacena la hora a la que se ejecutó la prueba de 
date_time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
process_output = process_output.split()
process_output.append(date_time)
print(process_output, type(process_output))

[b'Ping:', b'85.008', b'ms', b'Download:', b'68.61', b'Mbit/s', b'Upload:', b'37.95', b'Mbit/s', '2022-09-29 13:25:57'] <class 'list'>

In [11]:
# function to excute the speed test
def speedtest():
    # We need to store the time at which the speedtest was executed
    date_time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    # This is a string that contains what we would write on the command line 
    #to interface with speedtest.net
    speedtest_cmd = "speedtest-cli --simple"
    # We now execute the process: 
    process = subprocess.Popen(speedtest_cmd.split(), stdout=subprocess.PIPE)
    process_output = process.communicate()[0]
    process_output = process_output.split()
    # and we add the date and time 
    process_output.append(date_time)
    return process_output

### Parte 4: Guarde la salida de la funcion speedtest()

In [12]:
# Creamos un archivo 
with open("test.txt",'w') as f:
    f.write('test_msg')

In [13]:
# Verificamos que el archivo se haya abierto correctamente
with open("test.txt",'r') as f:
    str = f.read()
print(str)

test_msg

In [14]:
# funcion para guardar datos en csv
def save_to_csv(data, filename):
    try:
        #si el archivo existe, agregue una nueva linea con los 
        #resultados del experimento actual 
        with open(filename + '.csv', 'a') as f:
            # crear un objeto de escritura csv
            wr = csv.writer(f)
            # guardar (escribir) en el archivo
            wr.writerow(data)
    except:
        # si no exist, cree el archivo primero 
        with open(filename + '.csv', 'w') as f:
            # Sugerencia: esto es similar a agregar nuevas lineas a un archivo
            # crear un objeto de escritura csv
            re = csv.read(f)
            for row in spamreader:
            # guardar (escribir) en el archivo
                 print (', '.join(row))

### Paso 5: Verifique los datos recolectados

In [15]:
def print_from_csv(filename): 
    with open(filename + '.csv', 'r') as f:
        re = csv.reader(f)
        for row in re:
            print (', '.join(row))

### Paso 6: Ejecute varias veces Speedtest y guarde los datos

In [16]:
for i in range(5):
    # Measure internet speed (speedtest_output) using the speedtest() created earlier
    speedtest_output = speedtest()
    # Print the test number
    print ('Test number {}'.format(i))
    # Print the result (The needed variable is speedtest_output)
    print(speedtest_output)
    save_to_csv(speedtest_output, 'rpi_data_test')

Test number 0
['2022-09-29 13:25:57']
Test number 1
['2022-09-29 13:25:57']
Test number 2
['2022-09-29 13:25:58']
Test number 3
['2022-09-29 13:25:59']
Test number 4
['2022-09-29 13:26:00']

In [17]:
print_from_csv('rpi_data_test')

b'Ping:', b'26.755', b'ms', b'Download:', b'27.41', b'Mbit/s', b'Upload:', b'4.97', b'Mbit/s', 2022-09-28 21:15:01

b'Ping:', b'21.17', b'ms', b'Download:', b'29.99', b'Mbit/s', b'Upload:', b'5.04', b'Mbit/s', 2022-09-28 21:15:26

b'Ping:', b'27.187', b'ms', b'Download:', b'30.32', b'Mbit/s', b'Upload:', b'5.15', b'Mbit/s', 2022-09-28 21:15:50

b'Ping:', b'22.676', b'ms', b'Download:', b'13.00', b'Mbit/s', b'Upload:', b'4.18', b'Mbit/s', 2022-09-28 21:16:14

b'Ping:', b'18.405', b'ms', b'Download:', b'29.49', b'Mbit/s', b'Upload:', b'4.88', b'Mbit/s', 2022-09-28 21:16:39

2022-09-29 13:25:57

2022-09-29 13:25:57

2022-09-29 13:25:58

2022-09-29 13:25:59

2022-09-29 13:26:00

In [18]:
#for i in range(100):
 #   speedtest_output = speedtest()
  #  print ('Test number {}'.format(i))
   #  print(speedtest_output)
    # save_to_csv(speedtest_output, 'rpi_data_test')

# Parte 2: Manipule los datos

In [19]:
import datetime
import csv
import pandas as pd
import numpy as np

In [20]:
#Importar archivo
data_file = './Data/rpi_data_long.csv'

In [21]:
#parameto names: especifica el nombre de las columnas 
column_names = [ 'Type A', 'Measure A', 'Units A',
                 'Type B', 'Measure B', 'Units B',
                 'Type C', 'Measure C', 'Units C', 
                 'Datetime']

In [22]:
# read_csv: lee de data_file y asigna column_names como los 
# nombres de las columnas en el marco de datos 
with open(data_file, 'r') as f:
    df_redundant = pd.read_csv(f, names = column_names)

In [23]:
df_redundant.head()

,Type A,Measure A,Units A,Type B,Measure B,Units B,Type C,Measure C,Units C,Datetime
0,Ping:,26.992,ms,Download:,91.80,Mbit/s,Upload:,14.31,Mbit/s,2016-11-24 13:36:25
1,Ping:,24.532,ms,Download:,88.19,Mbit/s,Upload:,14.12,Mbit/s,2016-11-24 13:36:55
2,Ping:,20.225,ms,Download:,59.86,Mbit/s,Upload:,14.11,Mbit/s,2016-11-24 13:37:25
3,Ping:,19.332,ms,Download:,91.81,Mbit/s,Upload:,14.22,Mbit/s,2016-11-24 13:37:57
4,Ping:,22.494,ms,Download:,92.05,Mbit/s,Upload:,14.08,Mbit/s,2016-11-24 13:38:27

In [24]:
# ¿Cuál es el código para leer las primeras 20 líneas del archivo csv?
df_redundant.head(20)

,Type A,Measure A,Units A,Type B,Measure B,Units B,Type C,Measure C,Units C,Datetime
0,Ping:,26.992,ms,Download:,91.80,Mbit/s,Upload:,14.31,Mbit/s,2016-11-24 13:36:25
1,Ping:,24.532,ms,Download:,88.19,Mbit/s,Upload:,14.12,Mbit/s,2016-11-24 13:36:55
2,Ping:,20.225,ms,Download:,59.86,Mbit/s,Upload:,14.11,Mbit/s,2016-11-24 13:37:25
3,Ping:,19.332,ms,Download:,91.81,Mbit/s,Upload:,14.22,Mbit/s,2016-11-24 13:37:57
4,Ping:,22.494,ms,Download:,92.05,Mbit/s,Upload:,14.08,Mbit/s,2016-11-24 13:38:27
5,Ping:,17.586,ms,Download:,91.88,Mbit/s,Upload:,14.18,Mbit/s,2016-11-24 13:39:01
6,Ping:,21.835,ms,Download:,92.18,Mbit/s,Upload:,14.07,Mbit/s,2016-11-24 13:39:30
7,Ping:,20.464,ms,Download:,92.05,Mbit/s,Upload:,14.13,Mbit/s,2016-11-24 13:40:00
8,Ping:,19.293,ms,Download:,90.79,Mbit/s,Upload:,14.14,Mbit/s,2016-11-24 13:40:30
9,Ping:,20.354,ms,Download:,92.64,Mbit/s,Upload:,14.07,Mbit/s,2016-11-24 13:41:00
10,Ping:,19.01,ms,Download:,91.86,Mbit/s,Upload:,14.38,Mbit/s,2016-11-24 13:41:30
11,Ping:,18.092,ms,Download:,92.24,Mbit/s,Upload:,14.23,Mbit/s,2016-11-24 13:42:00
12,Ping:,18.137,ms,Download:,91.64,Mbit/s,Upload:,14.32,Mbit/s,2016-11-24 13:42:30
13,Ping:,18.344,ms,Download:,92.85,Mbit/s,Upload:,14.20,Mbit/s,2016-11-24 13:43:00
14,Ping:,23.328,ms,Download:,92.21,Mbit/s,Upload:,14.20,Mbit/s,2016-11-24 13:43:29
15,Ping:,17.908,ms,Download:,92.24,Mbit/s,Upload:,11.36,Mbit/s,2016-11-24 13:43:59
16,Ping:,19.291,ms,Download:,92.41,Mbit/s,Upload:,14.03,Mbit/s,2016-11-24 13:44:31
17,Ping:,20.117,ms,Download:,90.39,Mbit/s,Upload:,14.17,Mbit/s,2016-11-24 13:45:01
18,Ping:,19.579,ms,Download:,92.55,Mbit/s,Upload:,14.06,Mbit/s,2016-11-24 13:45:32
19,Ping:,16.364,ms,Download:,78.51,Mbit/s,Upload:,13.71,Mbit/s,2016-11-24 13:46:02

### Paso 3: cree una representacion concisa

In [25]:
# Copie df_redundant en otro marco de datos llamado df_compact mediante copy().
df_compact = df_redundant.copy()

In [26]:
# Cambiamos el nombre de las columnas en la relacion 
df_compact.rename(columns={'Measure A':'Ping (ms)', 
                           'Measure B': 'Download (Mbit/s)',
                           'Measure C': 'Upload (Mbit/s)'}, inplace=True)
df_compact.head(3)

,Type A,Ping (ms),Units A,Type B,Download (Mbit/s),Units B,Type C,Upload (Mbit/s),Units C,Datetime
0,Ping:,26.992,ms,Download:,91.80,Mbit/s,Upload:,14.31,Mbit/s,2016-11-24 13:36:25
1,Ping:,24.532,ms,Download:,88.19,Mbit/s,Upload:,14.12,Mbit/s,2016-11-24 13:36:55
2,Ping:,20.225,ms,Download:,59.86,Mbit/s,Upload:,14.11,Mbit/s,2016-11-24 13:37:25

In [27]:
# Como las columnas de los tipos y las unidades ya no son necesarias,estas columnas pueden descartarse.
df_compact.drop(['Type A', 'Type B', 'Type C',
         'Units A', 'Units B', 'Units C'], axis=1, inplace=True)
df_compact.head()

  Ping (ms) Download (Mbit/s)  Upload (Mbit/s)             Datetime
0    26.992             91.80            14.31  2016-11-24 13:36:25
1    24.532             88.19            14.12  2016-11-24 13:36:55
2    20.225             59.86            14.11  2016-11-24 13:37:25
3    19.332             91.81            14.22  2016-11-24 13:37:57
4    22.494             92.05            14.08  2016-11-24 13:38:27

### Paso 4: Separe los datos en dos columnas

In [28]:
# Aplique la función lambda para iterar a través del marco de datos y dividir la fecha de la columna Datetime.
df_compact['Date'] = df_compact['Datetime'].apply(lambda dt_str: pd.to_datetime(dt_str).date())

In [29]:
# Repita el paso a para dividir la hora de la columna Datetime.
temp = df_compact['Datetime'].apply(lambda dt_str: pd.to_datetime(dt_str))
df_compact['Time'] = temp.dt.time

In [33]:
# Ingrese el codigo para descartar la columna Datatime en la celda 
df_compact.drop(['Datetime'], axis=1)

    Ping (ms)    Download (Mbit/s)  Upload (Mbit/s)        Date      Time
0      26.992                91.80            14.31  2016-11-24  13:36:25
1      24.532                88.19            14.12  2016-11-24  13:36:55
2      20.225                59.86            14.11  2016-11-24  13:37:25
3      19.332                91.81            14.22  2016-11-24  13:37:57
4      22.494                92.05            14.08  2016-11-24  13:38:27
..        ...                  ...              ...         ...       ...
675  retrieve  2016-11-24 19:18:03              NaN         NaT       NaT
676  retrieve  2016-11-24 19:18:06              NaN         NaT       NaT
677  retrieve  2016-11-24 19:18:10              NaN         NaT       NaT
678  retrieve  2016-11-24 19:18:13              NaN         NaT       NaT
679    22.175                85.69            14.23  2016-11-24  19:18:16

[680 rows x 5 columns]

In [35]:
# Ingrese el codigo para imprimir las primeras 3 filas del marco de datos para verificar los cambios 
df_compact.head(3)

,Ping (ms),Download (Mbit/s),Upload (Mbit/s),Datetime,Date,Time
0,26.992,91.80,14.31,2016-11-24 13:36:25,2016-11-24,13:36:25
1,24.532,88.19,14.12,2016-11-24 13:36:55,2016-11-24,13:36:55
2,20.225,59.86,14.11,2016-11-24 13:37:25,2016-11-24,13:37:25

In [36]:
# Utilice la funcion type para imprimir el tipo de variable de los valores en la columnas Date y Time 
print(df_compact['Date'][0], type(df_compact['Date'][0]) )
print(df_compact['Time'][0], type(df_compact['Time'][0]) )

2016-11-24 <class 'datetime.date'>
13:36:25 <class 'datetime.time'>

### Paso 5: Guarde el nuevo marco de datos

In [37]:
# Guarde el marco de datos de pandas df_compact como un archivo csv en rpi_data_compact.csv
df_compact.to_csv('./Data/rpi_data_compact.csv')